# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: gossip/message.proto for package 'gossip'
# Original file comments:
# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'gossip/message_pb'

module Gossip
  module Gossip
    # Gossip
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gossip.Gossip'

      # GossipStream is the gRPC stream used for sending and receiving messages
      rpc :GossipStream, stream(::Gossip::Envelope), stream(::Gossip::Envelope)
      # Ping is used to probe a remote peer's aliveness
      rpc :Ping, ::Gossip::Empty, ::Gossip::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
