require:
  - rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    # exclude protoc generated code
    - 'lib/gateway/*'
    - 'lib/common/*'
    - 'lib/gossip/*'
    - 'lib/msp/*'
    - 'lib/orderer/*'
    - 'lib/peer/*'


