# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/chaincode.proto

require 'common/policies_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("peer/chaincode.proto", :syntax => :proto3) do
    add_message "protos.ChaincodeID" do
      optional :path, :string, 1
      optional :name, :string, 2
      optional :version, :string, 3
    end
    add_message "protos.ChaincodeInput" do
      repeated :args, :bytes, 1
      map :decorations, :string, :bytes, 2
      optional :is_init, :bool, 3
    end
    add_message "protos.ChaincodeSpec" do
      optional :type, :enum, 1, "protos.ChaincodeSpec.Type"
      optional :chaincode_id, :message, 2, "protos.ChaincodeID"
      optional :input, :message, 3, "protos.ChaincodeInput"
      optional :timeout, :int32, 4
    end
    add_enum "protos.ChaincodeSpec.Type" do
      value :UNDEFINED, 0
      value :GOLANG, 1
      value :NODE, 2
      value :CAR, 3
      value :JAVA, 4
    end
    add_message "protos.ChaincodeDeploymentSpec" do
      optional :chaincode_spec, :message, 1, "protos.ChaincodeSpec"
      optional :code_package, :bytes, 3
    end
    add_message "protos.ChaincodeInvocationSpec" do
      optional :chaincode_spec, :message, 1, "protos.ChaincodeSpec"
    end
    add_message "protos.LifecycleEvent" do
      optional :chaincode_name, :string, 1
    end
    add_message "protos.CDSData" do
      optional :hash, :bytes, 1
      optional :metadatahash, :bytes, 2
    end
    add_message "protos.ChaincodeData" do
      optional :name, :string, 1
      optional :version, :string, 2
      optional :escc, :string, 3
      optional :vscc, :string, 4
      optional :policy, :message, 5, "common.SignaturePolicyEnvelope"
      optional :data, :bytes, 6
      optional :id, :bytes, 7
      optional :instantiation_policy, :message, 8, "common.SignaturePolicyEnvelope"
    end
  end
end

module Protos
  ChaincodeID = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeID").msgclass
  ChaincodeInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeInput").msgclass
  ChaincodeSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeSpec").msgclass
  ChaincodeSpec::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeSpec.Type").enummodule
  ChaincodeDeploymentSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeDeploymentSpec").msgclass
  ChaincodeInvocationSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeInvocationSpec").msgclass
  LifecycleEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.LifecycleEvent").msgclass
  CDSData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.CDSData").msgclass
  ChaincodeData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeData").msgclass
end
