# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/proposal_response.proto

require 'google/protobuf/timestamp_pb'
require 'common/policies_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("peer/proposal_response.proto", :syntax => :proto3) do
    add_message "protos.ProposalResponse" do
      optional :version, :int32, 1
      optional :timestamp, :message, 2, "google.protobuf.Timestamp"
      optional :response, :message, 4, "protos.Response"
      optional :payload, :bytes, 5
      optional :endorsement, :message, 6, "protos.Endorsement"
      optional :interest, :message, 7, "protos.ChaincodeInterest"
    end
    add_message "protos.Response" do
      optional :status, :int32, 1
      optional :message, :string, 2
      optional :payload, :bytes, 3
    end
    add_message "protos.ProposalResponsePayload" do
      optional :proposal_hash, :bytes, 1
      optional :extension, :bytes, 2
    end
    add_message "protos.Endorsement" do
      optional :endorser, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "protos.ChaincodeInterest" do
      repeated :chaincodes, :message, 1, "protos.ChaincodeCall"
    end
    add_message "protos.ChaincodeCall" do
      optional :name, :string, 1
      repeated :collection_names, :string, 2
      optional :no_private_reads, :bool, 3
      optional :no_public_writes, :bool, 4
      repeated :key_policies, :message, 5, "common.SignaturePolicyEnvelope"
      optional :disregard_namespace_policy, :bool, 6
    end
  end
end

module Protos
  ProposalResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ProposalResponse").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Response").msgclass
  ProposalResponsePayload = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ProposalResponsePayload").msgclass
  Endorsement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Endorsement").msgclass
  ChaincodeInterest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeInterest").msgclass
  ChaincodeCall = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.ChaincodeCall").msgclass
end
