# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gateway/gateway.proto

require 'peer/chaincode_event_pb'
require 'peer/proposal_pb'
require 'peer/proposal_response_pb'
require 'peer/transaction_pb'
require 'common/common_pb'
require 'orderer/ab_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("gateway/gateway.proto", :syntax => :proto3) do
    add_message "gateway.EndorseRequest" do
      optional :transaction_id, :string, 1
      optional :channel_id, :string, 2
      optional :proposed_transaction, :message, 3, "protos.SignedProposal"
      repeated :endorsing_organizations, :string, 4
    end
    add_message "gateway.EndorseResponse" do
      optional :prepared_transaction, :message, 1, "common.Envelope"
    end
    add_message "gateway.SubmitRequest" do
      optional :transaction_id, :string, 1
      optional :channel_id, :string, 2
      optional :prepared_transaction, :message, 3, "common.Envelope"
    end
    add_message "gateway.SubmitResponse" do
    end
    add_message "gateway.SignedCommitStatusRequest" do
      optional :request, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "gateway.CommitStatusRequest" do
      optional :transaction_id, :string, 1
      optional :channel_id, :string, 2
      optional :identity, :bytes, 3
    end
    add_message "gateway.CommitStatusResponse" do
      optional :result, :enum, 1, "protos.TxValidationCode"
      optional :block_number, :uint64, 2
    end
    add_message "gateway.EvaluateRequest" do
      optional :transaction_id, :string, 1
      optional :channel_id, :string, 2
      optional :proposed_transaction, :message, 3, "protos.SignedProposal"
      repeated :target_organizations, :string, 4
    end
    add_message "gateway.EvaluateResponse" do
      optional :result, :message, 1, "protos.Response"
    end
    add_message "gateway.SignedChaincodeEventsRequest" do
      optional :request, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "gateway.ChaincodeEventsRequest" do
      optional :channel_id, :string, 1
      optional :chaincode_id, :string, 2
      optional :identity, :bytes, 3
      optional :start_position, :message, 4, "orderer.SeekPosition"
    end
    add_message "gateway.ChaincodeEventsResponse" do
      repeated :events, :message, 1, "protos.ChaincodeEvent"
      optional :block_number, :uint64, 2
    end
    add_message "gateway.ErrorDetail" do
      optional :address, :string, 1
      optional :msp_id, :string, 2
      optional :message, :string, 3
    end
    add_message "gateway.ProposedTransaction" do
      optional :transaction_id, :string, 1
      optional :proposal, :message, 2, "protos.SignedProposal"
      repeated :endorsing_organizations, :string, 3
    end
    add_message "gateway.PreparedTransaction" do
      optional :transaction_id, :string, 1
      optional :envelope, :message, 2, "common.Envelope"
    end
  end
end

module Gateway
  EndorseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.EndorseRequest").msgclass
  EndorseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.EndorseResponse").msgclass
  SubmitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.SubmitRequest").msgclass
  SubmitResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.SubmitResponse").msgclass
  SignedCommitStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.SignedCommitStatusRequest").msgclass
  CommitStatusRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.CommitStatusRequest").msgclass
  CommitStatusResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.CommitStatusResponse").msgclass
  EvaluateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.EvaluateRequest").msgclass
  EvaluateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.EvaluateResponse").msgclass
  SignedChaincodeEventsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.SignedChaincodeEventsRequest").msgclass
  ChaincodeEventsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.ChaincodeEventsRequest").msgclass
  ChaincodeEventsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.ChaincodeEventsResponse").msgclass
  ErrorDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.ErrorDetail").msgclass
  ProposedTransaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.ProposedTransaction").msgclass
  PreparedTransaction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("gateway.PreparedTransaction").msgclass
end
