# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderer/ab.proto

require 'common/common_pb'
require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("orderer/ab.proto", :syntax => :proto3) do
    add_message "orderer.BroadcastResponse" do
      optional :status, :enum, 1, "common.Status"
      optional :info, :string, 2
    end
    add_message "orderer.SeekNewest" do
    end
    add_message "orderer.SeekOldest" do
    end
    add_message "orderer.SeekSpecified" do
      optional :number, :uint64, 1
    end
    add_message "orderer.SeekNextCommit" do
    end
    add_message "orderer.SeekPosition" do
      oneof :Type do
        optional :newest, :message, 1, "orderer.SeekNewest"
        optional :oldest, :message, 2, "orderer.SeekOldest"
        optional :specified, :message, 3, "orderer.SeekSpecified"
        optional :next_commit, :message, 4, "orderer.SeekNextCommit"
      end
    end
    add_message "orderer.SeekInfo" do
      optional :start, :message, 1, "orderer.SeekPosition"
      optional :stop, :message, 2, "orderer.SeekPosition"
      optional :behavior, :enum, 3, "orderer.SeekInfo.SeekBehavior"
      optional :error_response, :enum, 4, "orderer.SeekInfo.SeekErrorResponse"
    end
    add_enum "orderer.SeekInfo.SeekBehavior" do
      value :BLOCK_UNTIL_READY, 0
      value :FAIL_IF_NOT_READY, 1
    end
    add_enum "orderer.SeekInfo.SeekErrorResponse" do
      value :STRICT, 0
      value :BEST_EFFORT, 1
    end
    add_message "orderer.DeliverResponse" do
      oneof :Type do
        optional :status, :enum, 1, "common.Status"
        optional :block, :message, 2, "common.Block"
      end
    end
  end
end

module Orderer
  BroadcastResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.BroadcastResponse").msgclass
  SeekNewest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.SeekNewest").msgclass
  SeekOldest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.SeekOldest").msgclass
  SeekSpecified = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.SeekSpecified").msgclass
  SeekNextCommit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.SeekNextCommit").msgclass
  SeekPosition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.SeekPosition").msgclass
  SeekInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.SeekInfo").msgclass
  SeekInfo::SeekBehavior = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.SeekInfo.SeekBehavior").enummodule
  SeekInfo::SeekErrorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.SeekInfo.SeekErrorResponse").enummodule
  DeliverResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("orderer.DeliverResponse").msgclass
end
